---
project_name: jdownloader-cli
release:
  github:
    owner: rkosegi
    name: jdownloader-cli
  name_template: '{{.Tag}}'
builds:
  - id: jdownloader-cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"
    gomips:
      - hardfloat
    goamd64:
      - v1
    targets:
      - linux_amd64_v1
      - linux_arm64
      - darwin_amd64_v1
      - darwin_arm64
      - windows_amd64_v1
      - windows_arm64
    dir: .
    main: cmd/cli.go
    binary: jdownloader-cli
    ldflags:
      - -s -w
      - -X github.com/tinng81/jdownloader-cli/internal.Version={{.Version}}
      - -X github.com/tinng81/jdownloader-cli/internal.Revision={{.Commit}}
      - -X github.com/tinng81/jdownloader-cli/internal.Branch={{.Tag}}
      - -X github.com/tinng81/jdownloader-cli/internal.BuildDate={{.Date}}
      - -X github.com/tinng81/jdownloader-cli/internal.BuildUser={{.Env.USER}}
archives:
  - format: binary
